apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-efs-csi-pv-provisioner-root
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Mi
