apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-efs-csi-pv-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-efs-csi-pv-provisioner
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-efs-csi-pv-provisioner
subjects:
- kind: ServiceAccount
  name: aws-efs-csi-pv-provisioner
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: aws-efs-csi-pv-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-efs-csi-pv-provisioner
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-efs-csi-pv-provisioner
subjects:
- kind: ServiceAccount
  name: aws-efs-csi-pv-provisioner
roleRef:
  kind: Role
  name: aws-efs-csi-pv-provisioner
  apiGroup: rbac.authorization.k8s.io
