apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-efs-csi-pv-provisioner.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-efs-csi-pv-provisioner.serviceAccountName" . }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ include "aws-efs-csi-pv-provisioner.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
