apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aws-efs-csi-pv-provisioner.serviceAccountName" . }}
  labels:
    {{- include "aws-efs-csi-pv-provisioner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
